{
    "__comment":"テストテーブル取得用関数群",
    "title__comment":"日本語表記名",
    "title":"テスト",
    "tableName__comment":"DBテーブル名",
    "tableName":"m_test",
    "columnList__comment":"DBテーブルカラム一覧",
    "columnList":[
        "id",
        "name",
        "sort_id",
        "status",
        "regist_date",
        "edit_date"
    ],
    "selectList__comment":"対象カラム単独一覧取得関数",
    "selectList":[
        {
            "title":"名前",
            "key":"Name",
            "name":"name"
        }
    ],
    "choiceList__comment":"IDから取得、逆引き取得、存在確認関数生成",
    "choiceList":[
        {
            "title":"名前",
            "key":"Name",
            "name":"name"
        },
        {
            "title":"順番",
            "key":"SortId",
            "name":"sort_id"
        }
    ],
    "constOnly__comment":"定数宣言のみ",
    "constOnly":[
        {
            "title":"ID生成文字数",
            "key":"ID_STR_NUM",
            "val":"10"
        }
    ],
    "constSet__comment":"定数宣言および、処理用関数",
    "constSet":{
        "STATUS":{
            "title":"表示ステータス",
            "key":"Status",
            "data":[
                {
                    "key":"OK",
                    "val":"1",
                    "name":"OKです"
                },
                {
                    "key":"NG",
                    "val":"-1",
                    "name":"NGです"
                }
            ]
        }
    }
}
